### ISSUE TITLE
Space in the path

### ISSUE THREAD

**Issue by Buzzroid** [Skycoder42/qdep#2]
It does not work if space in the path on Windows, due to the python path limit.
For example, the user id has a space ("The Open")

`python C:/Users/The Open/AppData/Local/qdep/qdep/Cache/f85885b167045f8bab38a8514b846c5352b13f6119a4c562f8ef964b181ae6f0/1.4.1/qxmlcodegen.py
python: can't open file 'C:/Users/The': [Errno 2] No such file or directory`

**Comment by Buzzroid** [comment]
Setting QDEP_CACHE_DIR could be a remedy.

**Comment by Skycoder42** [comment]
Thanks for reporting this. I would still consider it a bug, as spaces in the path should not break qdep. Reopening the issue until fixed

**Comment by Skycoder42** [comment]
... and closing it again. This is not an issue of qdep, but of the module you are referring to, https://github.com/Skycoder42/QXmlCodeGen. I have created an issue there, copying this one

**Comment by Skycoder42** [comment]
Please note: While https://github.com/Skycoder42/QXmlCodeGen/issues/1 was fixed, projects that use it (like QtRestClient and QtMvvm) must first update their reference to it before the problem gets solved there. Until that happens, you can manually do so by explicitly specifying 1.4.2 as version.
