### ISSUE TITLE
Question about DEPRECATION: Python 2.7

### ISSUE THREAD

**Issue by Light-Wizzard** [Skycoder42/qdep#5]
Both Travis and AppVeyor give this warning, with an error:
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020

GitHub example:
https://github.com/Light-Wizzard/EchoReloadedService

Travis:
https://travis-ci.org/github/Light-Wizzard/EchoReloadedService

AppVeyor:
https://ci.appveyor.com/project/Light-Wizzard/echoreloadedservice

I did install Python 2.7

Any chance of upgrading to a newer python version?

Thanks, Flesh

**Comment by Skycoder42** [comment]
I am using python3 only, so no idea where this warning comes from
